name: Hyperliquid OHLC Data Puller

on:
  schedule:
    # Runs every 30 minutes as requested
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  pull-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create downloads directory
      run: mkdir -p downloads
      
    - name: Download previous data (if exists)
      uses: actions/download-artifact@v4
      with:
        name: ohlc-data
        path: downloads
      continue-on-error: true
      
    - name: Run data puller
      env:
        GITHUB_ACTIONS: 'true'
        DATA_FOLDER: './downloads'
      run: |
        python hyperliquid_puller.py
        
    - name: Upload data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ohlc-data
        path: downloads/
        retention-days: 90
        
    - name: Log completion
      run: |
        echo "Data pull completed at $(date)"
        ls -la downloads/
