name: Hyperliquid OHLC Data Puller

permissions:
  contents: write  # Allow workflow to commit files

on:
  schedule:
    # Runs every 30 minutes as requested
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  pull-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run data puller
      env:
        GITHUB_ACTIONS: 'true'
        DATA_FOLDER: './data'
      run: |
        python hyperliquid_puller.py
        
    - name: Check generated data
      run: |
        echo "Generated data files:"
        ls -la data/
        echo "Total CSV files: $(find data -name "*.csv" | wc -l)"
        
    - name: Commit and push data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add data files
        git add data/
        
        # Check if there are any changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          # Commit with timestamp
          git commit -m "Update Hyperliquid data - $(date)"
          git push
          echo "✅ Data committed and pushed to repository"
        fi
